
version: 2
services:
  event_stores:
    - type: stdout
  object_stores:
    - type: stdout
stacks:
  basic_reporting:
    plugins:
- type: access_logs
  config:
    mode: full # (summary|details|full)
    format: console # (json|console)
    rules:
      - name: full log httpbin.org
        expr: request.host == "httpbin.com"
        mode: full
      - name: details log on 500
        expr: response.status >= 500
        mode: details
      - name: full log on 400
        expr: response.status >= 400 && response.status < 500
        mode: full

      - type: report_usage
tap:
  direction: egress-external
  ignore_loopback: true
  audit_include_dns: false
  http:
    stack: basic_reporting
