version: 2
services:
  event_stores:
    - type: stdout
  object_stores:
    - type: stdout
stacks:
  basic_reporting:
    plugins:
      - type: access_logs
        config:
          mode: details
          format: console
      - type: report_usage
tap:
  direction: egress-external
  ignore_loopback: true
  audit_include_dns: false
  http:
    stack: basic_reporting
